### ISSUE TITLE
Not founding .nuxt/analyze/base on "Download base branch bundle stats" step

### ISSUE THREAD

**Issue by blv-rubendiaz** [wattanx/nuxt-bundle-analysis#4]
I'm trying to use that action to include the nuxt bundle analysis in an already existing project and it end up with that error:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/109732708/185155997-39c63837-a763-464f-ac12-951098d83c43.png">

It is trying to get the base branch bundle stats which was never generate, it is an issue or it is must to have in order to make it works?

**Comment by wattanx** [comment]
Since this Actions works by comparing the base bundle to each PR, the first time it is run it will fail because there is no base to compare.

Ideally, the changes would be committed directly to the default branch, where the base bundle would be generated, and the subsequent branch would be a valid comparison so that the script would work as expected.

Actions are executed at each timing of merge into the main branch or PR as follows.

### Execute at the timing of merge to main branch

1. calculate the bundle size of the main branch

2. save the bundle size of 1 in Artifact of GitHub Actions

### Execute at the timing of PR

1. calculate bundle size of working branch when PR is created
2. download the bundle size of the Artifact saved in the Actions executed at the timing of the last merge.
3. compare the bundle size of 1 with the bundle size of 2 and calculate the difference
4. comment the result of 3 in PR

**Comment by blv-rubendiaz** [comment]
Thanks @wattanx, I already figure it how to handle it and I will consider your comments accordingly. ❤️
